version: '2'
services:
  mysql:
    build: ./mysql
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    command:
      - "--innodb_use_native_aio=0"
    container_name: mysql
  mongo:
    build: ./mongo
    volumes:
      - ${DATA_PATH}/mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017
    container_name: mongo
  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    container_name: redis
  postgres:
    build: ./postgres
    volumes:
      - ${DATA_PATH}/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    container_name: postgres
